WORK_EVENTS = [
    # ----------------- 35 SỰ KIỆN GAIN (NHẬN TIỀN) -----------------
    {"type": "gain", "min_amount": 100, "max_amount": 500, "text": "Bạn đi quét lá ngoài công viên, tình cờ quét luôn tờ vé số trúng giải đặc biệt của ông chú đang ngủ gật. Bạn lén đem đổi và nhận được {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 700, "text": "Bạn mở dịch vụ xem bói online. Dù chỉ phán bừa dựa trên Google, khách hàng vẫn tin sái cổ và donate cho bạn {amount} điểm."},
    {"type": "gain", "min_amount": 200, "max_amount": 800, "text": "Đang đi bộ thì vấp phải cục gạch. Bạn tính chửi thề nhưng phát hiện dưới cục gạch là {amount} điểm do ai đó đánh rơi. Ấm no!"},
    {"type": "gain", "min_amount": 150, "max_amount": 600, "text": "Bạn làm YouTuber review ẩm thực, đi ăn bún bò khen ngon quá đáng khiến quán đông nghịt. Chủ quán chia hoa hồng cho bạn {amount} điểm."},
    {"type": "gain", "min_amount": 300, "max_amount": 1000, "text": "Thử làm thợ code dạo, copy paste code từ StackOverflow nhưng vô tình fix được lỗi server triệu đô. Sếp thưởng nóng {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 400, "text": "Đi phụ hồ nhưng múa muôi xây tường quá nghệ thuật, được lên tóp tóp xu hướng. Nhãn hàng xi măng book quảng cáo trả {amount} điểm."},
    {"type": "gain", "min_amount": 200, "max_amount": 500, "text": "Tham gia gameshow 'Thách thức danh hài', bạn vừa bước ra chưa nói gì đã trượt chân ngã sấp mặt. Khán giả cười bò, bạn ẵm luôn {amount} điểm."},
    {"type": "gain", "min_amount": 150, "max_amount": 450, "text": "Mở tiệm net cỏ nhưng bị mất mạng cả ngày. Khách bực quá bỏ về quên luôn tiền thối, bạn đút túi được {amount} điểm."},
    {"type": "gain", "min_amount": 500, "max_amount": 1000, "text": "Nhận kèo dọn nhà thuê cho đại gia, bạn vô tình tìm thấy quỹ đen của ổng giấu trong gầm giường. Đại gia đưa {amount} điểm phí bịt miệng."},
    {"type": "gain", "min_amount": 100, "max_amount": 350, "text": "Làm shipper giao hàng vào lúc 12h đêm. Giao xong sợ ma chạy thục mạng, hôm sau phát hiện khách tip nhầm {amount} điểm vì tưởng bạn là VĐV điền kinh."},
    {"type": "gain", "min_amount": 200, "max_amount": 700, "text": "Mở lớp dạy 'Cách làm giàu nhanh chóng'. Học phí mỗi người là 10 điểm. Bạn lùa gà và thu về {amount} điểm rồi chạy mất dép."},
    {"type": "gain", "min_amount": 150, "max_amount": 650, "text": "Bán kem mùa đông nhưng PR là 'Kem rèn luyện ý chí'. Mấy giang hồ hảo hán mua ầm ầm, lãi ngay {amount} điểm."},
    {"type": "gain", "min_amount": 300, "max_amount": 900, "text": "Hack vào hệ thống trường học định sửa điểm môn Toán, nhưng lỡ tay bấm nhầm nút chuyển tiền thưởng sinh viên ưu tú vào túi mình. Bạn vớ được {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 500, "text": "Đóng giả tượng đồng ngoài phố đi bộ mỏi nhừ cả chân. Một con chó tè vào chân bạn nhưng bạn vẫn đứng im. Khán giả nể phục ném vào nón {amount} điểm."},
    {"type": "gain", "min_amount": 120, "max_amount": 420, "text": "Làm part-time tại rạp chiếu phim, lúc đi dọn rác vớt được {amount} điểm giấu trong hũ bắp rang bơ thừa."},
    {"type": "gain", "min_amount": 200, "max_amount": 600, "text": "Livestream ngủ 8 tiếng, tỉnh dậy thấy view chót vót và khán giả donate {amount} điểm vì bạn ngáy theo nhịp điệu nhạc EDM."},
    {"type": "gain", "min_amount": 250, "max_amount": 800, "text": "Giúp bà cụ sang đường, hóa ra bà là tỷ phú ẩn danh. Bà chê bạn mặc đồ rách rưới quá nên ném cho {amount} điểm đi mua đồ mới."},
    {"type": "gain", "min_amount": 100, "max_amount": 300, "text": "Tham gia thi ăn xúc xích, bạn lén giấu một nửa vào túi quần và vẫn đoạt giải nhất mang về {amount} điểm."},
    {"type": "gain", "min_amount": 150, "max_amount": 400, "text": "Viết truyện ngôn tình nam chính là tổng tài bốc vác. Sách bán chạy bất ngờ, nhuận bút nhận được {amount} điểm."},
    {"type": "gain", "min_amount": 300, "max_amount": 800, "text": "Thiết kế logo cho công ty đa quốc gia bằng Paint trong 3 phút. Giám đốc khen nức nở độ 'minimalism' và chuyển khoản {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 500, "text": "Làm quản trị viên cho một group bóc phốt. Ăn tiền 'bảo kê' xóa bài của mấy idol tóp tóp, đút túi {amount} điểm."},
    {"type": "gain", "min_amount": 200, "max_amount": 700, "text": "Đầu tư vào tiền ảo coin hệ chó mèo. Vừa mua xong thì Elon Musk tweet linh tinh, coin bay tung nóc, chốt lời {amount} điểm."},
    {"type": "gain", "min_amount": 150, "max_amount": 450, "text": "Trồng rau bán ngoài chợ, bạn hét giá x3 vì quảng cáo là rau được nghe nhạc Beethoven mỗi ngày. Lời được {amount} điểm."},
    {"type": "gain", "min_amount": 250, "max_amount": 900, "text": "Bắt được chó đi lạc của phú bà, mang trả được hậu tạ {amount} điểm. Sau này mới biết phú bà nuôi tận 10 con giống hệt vậy."},
    {"type": "gain", "min_amount": 100, "max_amount": 350, "text": "Khởi nghiệp bán trà đá vỉa hè. Pha nước lã với ít màu thực phẩm, khách uống khen sảng khoái. Lãi {amount} điểm."},
    {"type": "gain", "min_amount": 200, "max_amount": 600, "text": "Làm thợ sửa xe hơi, rớt ốc vít vô trong động cơ nhưng làm lơ. Khách đi thấy tiếng kêu lạ tưởng xe độ bô, thưởng cho {amount} điểm."},
    {"type": "gain", "min_amount": 150, "max_amount": 500, "text": "Gấp hạc giấy bán trước cổng trường mầm non với giá cắt cổ vì quảng cáo là hạc thần kỳ. Bào được của các bé {amount} điểm."},
    {"type": "gain", "min_amount": 300, "max_amount": 1000, "text": "Tham gia đào vàng ở mỏ Angelic, đào đúng một phát trúng mỏ kim cương. Kiếm đậm {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 300, "text": "Tham gia giải chạy bộ mầm non, bế nhầm cháu người khác cắm đầu chạy về đích. Ban tổ chức bối rối trao giải {amount} điểm cho bạn."},
    {"type": "gain", "min_amount": 200, "max_amount": 650, "text": "Bán khóa học 'Làm thế nào để ngủ 16 tiếng một ngày mà không bị mẹ chửi'. Thu hút hàng ngàn thanh niên, lãi {amount} điểm."},
    {"type": "gain", "min_amount": 250, "max_amount": 800, "text": "Bắt trộm vào nhà hàng xóm, hóa ra ông hàng xóm đang giấu vợ mua PS5. Ông nhét vào tay bạn {amount} điểm bảo coi như chưa thấy gì."},
    {"type": "gain", "min_amount": 150, "max_amount": 450, "text": "Hát karaoke dở đến mức mấy nhà xung quanh phải quyên góp {amount} điểm để bạn cất mic đi."},
    {"type": "gain", "min_amount": 200, "max_amount": 600, "text": "Làm gia sư Toán nhưng lại dạy học sinh chơi game leo rank. Học sinh rank Cao Thủ, phụ huynh vui vẻ thưởng {amount} điểm."},
    {"type": "gain", "min_amount": 300, "max_amount": 900, "text": "Đi đường vớ được một cây chổi chà, mang về bán đấu giá với nhãn 'Chổi bay của Harry Potter' và lừa được {amount} điểm."},
    {"type": "gain", "min_amount": 100, "max_amount": 400, "text": "Giả vờ làm pháp sư đuổi tà cho người ta. Múa may quay cuồng rớt cmn cả cái quần, gia chủ tưởng phép thuật mới nên donate {amount} điểm."},
    
    # ----------------- 15 SỰ KIỆN LOSE (MẤT TIỀN) -----------------
    {"type": "lose", "min_amount": 100, "max_amount": 500, "text": "Bạn giả vờ làm bác sĩ tiêm phòng, nhưng vì run tay tiêm trúng mông trưởng khoa. Bạn bị đuổi việc và phải đền bù {amount} điểm tiền thuốc."},
    {"type": "lose", "min_amount": 200, "max_amount": 600, "text": "Đi làm bảo vệ ngân hàng, buồn ngủ quá đem súng ra làm gối nằm. Cướp vô ôm tiền đi mất, bạn bị phạt {amount} điểm."},
    {"type": "lose", "min_amount": 150, "max_amount": 400, "text": "Mua phôi ép thẻ để làm bằng đại học giả, xui sao gặp đúng thầy hiệu trưởng đi mua thẻ điện thoại. Bạn mất trắng {amount} điểm chạy án."},
    {"type": "lose", "min_amount": 300, "max_amount": 800, "text": "Làm thợ cắt tóc, khách kêu hớt xíu mái thôi mà bạn lỡ tay đưa tông đơ đi một đường sân bay. Đền tiền tóc giả {amount} điểm."},
    {"type": "lose", "min_amount": 100, "max_amount": 500, "text": "Bốc vác ở chợ đầu mối, lỡ chân dẫm bẹp rổ trứng vịt lộn của bà bán hàng rong. Bị chửi xối xả và đền {amount} điểm."},
    {"type": "lose", "min_amount": 250, "max_amount": 750, "text": "Đăng ký làm diễn viên quần chúng đóng vai cái cây. Đứng ngứa quá gãi mông ngay lúc cam quay cận mặt. Đạo diễn trừ lương {amount} điểm."},
    {"type": "lose", "min_amount": 150, "max_amount": 450, "text": "Phát tờ rơi ngoài ngã tư, lười quá nên ném hết xuống cống. Công nhân vệ sinh bắt được bắt đền tiền thông cống {amount} điểm."},
    {"type": "lose", "min_amount": 200, "max_amount": 650, "text": "Làm quản lý quán trà sữa, lén uống vụng trân châu bị nghẹn. Tiền viện phí và tiền phạt tội ăn vụng tốn {amount} điểm."},
    {"type": "lose", "min_amount": 400, "max_amount": 1000, "text": "Đi trade coin theo hệ tâm linh, nến đỏ tưởng là màu may mắn nên all-in. Cháy mẹ tài khoản mất toi {amount} điểm."},
    {"type": "lose", "min_amount": 100, "max_amount": 300, "text": "Làm thợ lặn nhặt bóng golf, nhưng xui sao gặp phải cá sấu. Vứt đồ bơi chạy lấy mạng, thiệt hại {amount} điểm."},
    {"type": "lose", "min_amount": 200, "max_amount": 700, "text": "Ship bánh kem đám cưới nhưng đi vào ổ gà làm cái bánh bay thẳng vô mặt cô dâu. Bạn phải đền {amount} điểm chi phí trang điểm lại."},
    {"type": "lose", "min_amount": 150, "max_amount": 500, "text": "Nhận bốc họ nhưng gặp con nợ là Chí Phèo rạch mặt ăn vạ. Bị công an bế đi đóng phạt {amount} điểm."},
    {"type": "lose", "min_amount": 300, "max_amount": 900, "text": "Chơi đồ hàng ngoài công viên, giả vờ là kỹ sư cầu đường rồi phá banh cái xích đu của thiếu nhi. Đền tài sản công cộng {amount} điểm."},
    {"type": "lose", "min_amount": 100, "max_amount": 350, "text": "Làm phiên dịch viên tiếng Nhật mà toàn dùng Google Dịch. Dịch 'Kính gửi giám đốc' thành 'Đầu moi giám đốc'. Phạt {amount} điểm."},
    {"type": "lose", "min_amount": 250, "max_amount": 800, "text": "Bơm bánh xe dạo lỡ bơm căng quá làm nổ tung cái bánh xe siêu xe bò. Chạy thục mạng vẫn bị tóm, đền bù {amount} điểm."}
]
