"""
item_config.py — Bảng cấu hình trung tâm cho toàn bộ vật phẩm của bot.
Quy ước ID:
  0: Vé số
  11-20: Sự kiện (Event)
  21-30: Chợ đen (BM)
  31-40: Nhẫn (Ring)
  41-50: Quà (Gift)
  51-60: Nông trại (Farm)
  61-70: Lootbox
  71-80: Đồ ăn (Food)
  """

from typing import TypedDict

class ItemEntry(TypedDict):
    id: int
    name: str
    icon: str
    price: int | None
    description: str
    db_key: str
    category: str
    usable: bool

ITEM_REGISTRY: dict[int, ItemEntry] = {
    0: {
        "id":          0,
        "name":        "Vé Xổ Số",
        "icon":        "🎟️",
        "price":       50,
        "description": "Vé tham gia xổ số hàng ngày. Tối đa 200 vé/người.",
        "db_key":      "lottery_ticket",
        "category":    "event",
        "usable":      False,
    },
    11: {
        "id":          11,
        "name":        "Hộp Quà Bí Ẩn (Gacha)",
        "icon":        "<:gift_00_symbol:1536003307011842099>",
        "price":       2500,
        "description": "Mở ra phần thưởng ngẫu nhiên.",
        "db_key":      "item_1",
        "category":    "event",
        "usable":      True,
    },
    12: {
        "id":          12,
        "name":        "Role Màu Sự Kiện",
        "icon":        "🎭",
        "price":       10000,
        "description": "Nhận role màu trong 7 ngày.",
        "db_key":      "item_2",
        "category":    "event",
        "usable":      False,
    },
    13: {
        "id":          13,
        "name":        "Role Màu Thiết Kế Riêng",
        "icon":        "🎨",
        "price":       30000,
        "description": "Nhận role màu thiết kế riêng trong 30 ngày.",
        "db_key":      "item_3",
        "category":    "event",
        "usable":      False,
    },
    14: {
        "id":          14,
        "name":        "Role Biểu Tượng Vĩnh Viễn",
        "icon":        "👑",
        "price":       70000,
        "description": "Nhận role biểu tượng vĩnh viễn (Giới hạn: 5 slot).",
        "db_key":      "item_4",
        "category":    "event",
        "usable":      False,
    },
    15: {
        "id":          15,
        "name":        "Vật Phẩm Tối Cao",
        "icon":        "<:symbol_trophy:1537550568665649232>",
        "price":       110000,
        "description": "Nitro / Custom Đặc Quyền.",
        "db_key":      "item_5",
        "category":    "event",
        "usable":      False,
    },
    16: {
        "id":          16,
        "name":        "Thẻ Tăng Vận",
        "icon":        "✨",
        "price":       None,
        "description": "Tăng 50% tỉ lệ drop lootbox từ fish/mine/chop và tăng tỉ lệ rank cao khi mở hộp trong 30 phút.",
        "db_key":      "boost_card",
        "category":    "event",
        "usable":      True,
    },
    21: {
        "id":          21,
        "name":        "Bom Ảo Giác",
        "icon":        "💣",
        "price":       1500,
        "description": "Bot tag mục tiêu 3 lần liên tiếp rồi xóa ngay lập tức (Ghost Ping).",
        "db_key":      "ghost_ping_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    22: {
        "id":          22,
        "name":        "Búa Gõ 1 Phút",
        "icon":        "🔨",
        "price":       3000,
        "description": "Timeout mục tiêu 1 phút (cấm chat/voice).",
        "db_key":      "timeout_1m",
        "category":    "blackmarket",
        "usable":      True,
    },
    23: {
        "id":          23,
        "name":        "Thẻ Đổi Tên",
        "icon":        "🤡",
        "price":       5000,
        "description": "Buộc mục tiêu đổi biệt danh thành tên tấu hài tùy ý người dùng.",
        "db_key":      "nickname_change",
        "category":    "blackmarket",
        "usable":      True,
    },
    24: {
        "id":          24,
        "name":        "Bao Tay Đạo Chích",
        "icon":        "🧤",
        "price":       7000,
        "description": "Trộm ngẫu nhiên 50–500 điểm sự kiện của mục tiêu.",
        "db_key":      "thief_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    25: {
        "id":          25,
        "name":        "Thẻ Rút Phích Cắm",
        "icon":        "🔌",
        "price":       8000,
        "description": "Đá văng mục tiêu khỏi Voice Channel ngay lập tức.",
        "db_key":      "disconnect_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    26: {
        "id":          26,
        "name":        "Búa Gõ 5 Phút",
        "icon":        "🔨",
        "price":       10000,
        "description": "Timeout mục tiêu 5 phút (cấm chat/voice).",
        "db_key":      "timeout_5m",
        "category":    "blackmarket",
        "usable":      True,
    },
    27: {
        "id":          27,
        "name":        "Thẻ Miễn Nhiễm",
        "icon":        "🛡️",
        "price":       12000,
        "description": "Tự động chặn 1 lần bị người khác dùng thẻ xấu lên mình.",
        "db_key":      "shield_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    28: {
        "id":          28,
        "name":        "Thẻ Đặc Xá",
        "icon":        "🕊️",
        "price":       15000,
        "description": "Cứu người khác khỏi tù hoặc tự cứu mình.",
        "db_key":      "free_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    29: {
        "id":          29,
        "name":        "Thẻ Tống Giam",
        "icon":        "🚔",
        "price":       25000,
        "description": "Gửi 1 người vào chuồng chó (50 lần lau dọn).",
        "db_key":      "jail_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    30: {
        "id":          30,
        "name":        "Trát Hầu Tòa",
        "icon":        "📜",
        "price":       20000,
        "description": "Gửi một Embed dọa ban vĩnh viễn cực kỳ nghiêm trọng rồi chốt là đùa.",
        "db_key":      "fake_ban_card",
        "category":    "blackmarket",
        "usable":      True,
    },
    31: {
        "id":          31,
        "name":        "Nhẫn Cỏ",
        "icon":        "<:ring_01_grass:1535564483848572959>",
        "price":       1000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 31. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_31",
        "category":    "ring",
        "usable":      False,
    },
    32: {
        "id":          32,
        "name":        "Nhẫn Gỗ",
        "icon":        "<:ring_02_wood:1535564485530620005>",
        "price":       5000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 32. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_32",
        "category":    "ring",
        "usable":      False,
    },
    33: {
        "id":          33,
        "name":        "Nhẫn Đá",
        "icon":        "<:ring_03_stone:1535564487749533727>",
        "price":       15000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 33. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_33",
        "category":    "ring",
        "usable":      False,
    },
    34: {
        "id":          34,
        "name":        "Nhẫn Đồng",
        "icon":        "<:ring_04_copper:1535552601272098897>",
        "price":       30000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 34. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_34",
        "category":    "ring",
        "usable":      False,
    },
    35: {
        "id":          35,
        "name":        "Nhẫn Sắt",
        "icon":        "<:ring_05_iron:1535552603038023710>",
        "price":       60000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 35. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_35",
        "category":    "ring",
        "usable":      False,
    },
    36: {
        "id":          36,
        "name":        "Nhẫn Bạc",
        "icon":        "<:ring_06_silver:1535564489498427402>",
        "price":       100000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 36. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_36",
        "category":    "ring",
        "usable":      False,
    },
    37: {
        "id":          37,
        "name":        "Nhẫn Vàng",
        "icon":        "<:ring_07_gold:1535564491461369917>",
        "price":       150000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 37. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_37",
        "category":    "ring",
        "usable":      False,
    },
    38: {
        "id":          38,
        "name":        "Nhẫn Hồng Ngọc",
        "icon":        "<:ring_08_ruby:1535564493755523112>",
        "price":       250000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 38. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_38",
        "category":    "ring",
        "usable":      False,
    },
    39: {
        "id":          39,
        "name":        "Nhẫn Ngọc Lục Bảo",
        "icon":        "<:ring_09_emerald:1535552609669353492>",
        "price":       400000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 39. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_39",
        "category":    "ring",
        "usable":      False,
    },
    40: {
        "id":          40,
        "name":        "Nhẫn Kim Cương",
        "icon":        "<:ring_10_diamond:1535564495861055488>",
        "price":       800000,
        "description": "Dùng để cầu hôn bằng lệnh marry @user 40. (Xem chỉ số bằng lệnh marry)",
        "db_key":      "ring_40",
        "category":    "ring",
        "usable":      False,
    },
    41: {
        "id":          41,
        "name":        "Hoa Hồng",
        "icon":        "<:gift_41_rose:1536003308911857694>",
        "price":       500,
        "description": "+5 DTM. Một bông hoa nhỏ bé nhưng chứa đựng tình cảm chân thành.",
        "db_key":      "gift_41",
        "category":    "gift",
        "usable":      False,
    },
    42: {
        "id":          42,
        "name":        "Gấu Bông",
        "icon":        "<:gift_42_teddybear:1536003310857756742>",
        "price":       1500,
        "description": "+17.5 DTM. Gấu bông êm ái cho những cái ôm ấm áp.",
        "db_key":      "gift_42",
        "category":    "gift",
        "usable":      False,
    },
    43: {
        "id":          43,
        "name":        "Hộp Socola",
        "icon":        "<:gift_43_chocolate:1536003312628006922>",
        "price":       3000,
        "description": "+40.0 DTM. Ngọt ngào và quyến rũ như tình yêu thuở ban đầu.",
        "db_key":      "gift_43",
        "category":    "gift",
        "usable":      False,
    },
    44: {
        "id":          44,
        "name":        "Son Môi",
        "icon":        "<:gift_44_lipstick:1536003315182342144>",
        "price":       5000,
        "description": "+75.0 DTM. Thỏi son hàng hiệu quyến rũ.",
        "db_key":      "gift_44",
        "category":    "gift",
        "usable":      False,
    },
    45: {
        "id":          45,
        "name":        "Rượu Vang",
        "icon":        "<:gift_45_wine:1536003317153403000>",
        "price":       10000,
        "description": "+160.0 DTM. Đêm lãng mạn không thể thiếu chút men say.",
        "db_key":      "gift_45",
        "category":    "gift",
        "usable":      False,
    },
    46: {
        "id":          46,
        "name":        "Áo Đôi",
        "icon":        "<:gift_46_couple:1536003319179251744>",
        "price":       15000,
        "description": "+260.0 DTM. Khẳng định chủ quyền với cả thế giới.",
        "db_key":      "gift_46",
        "category":    "gift",
        "usable":      False,
    },
    47: {
        "id":          47,
        "name":        "Đồng Hồ",
        "icon":        "<:gift_47_watch:1536003321364746250>",
        "price":       25000,
        "description": "+475.0 DTM. Thời gian trôi qua, tình cảm vẫn đong đầy.",
        "db_key":      "gift_47",
        "category":    "gift",
        "usable":      False,
    },
    48: {
        "id":          48,
        "name":        "Dây Chuyền",
        "icon":        "<:gift_48_necklace:1536003323503579167>",
        "price":       50000,
        "description": "+1000.0 DTM. Kỷ vật lấp lánh sang trọng.",
        "db_key":      "gift_48",
        "category":    "gift",
        "usable":      False,
    },
    49: {
        "id":          49,
        "name":        "Siêu Xe",
        "icon":        "<:gift_49_supercar:1536003326502506506>",
        "price":       100000,
        "description": "+2200.0 DTM. Món quà dành cho giới siêu giàu.",
        "db_key":      "gift_49",
        "category":    "gift",
        "usable":      False,
    },
    50: {
        "id":          50,
        "name":        "Biệt Thự",
        "icon":        "<:gift_50_villa:1536003329002315786>",
        "price":       250000,
        "description": "+6000.0 DTM. Xây dựng tổ ấm hoàng gia.",
        "db_key":      "gift_50",
        "category":    "gift",
        "usable":      False,
    },
    51: {
        "id":          51,
        "name":        "Hạt Giống Lúa Mì",
        "icon":        "🌾",
        "price":       100,
        "description": "Cây cơ bản, thu hoạch sau 30 phút.",
        "db_key":      "seed_wheat",
        "category":    "farm",
        "usable":      False,
    },
    52: {
        "id":          52,
        "name":        "Hạt Giống Khoai Tây",
        "icon":        "🥔",
        "price":       200,
        "description": "Thu hoạch sau 1 tiếng. 20% cơ hội nhân đôi sản lượng!",
        "db_key":      "seed_potato",
        "category":    "farm",
        "usable":      False,
    },
    53: {
        "id":          53,
        "name":        "Hạt Giống Cà Chua",
        "icon":        "🍅",
        "price":       400,
        "description": "Thu hoạch sau 3 tiếng. Nguyên liệu Mứt Cà Chua.",
        "db_key":      "seed_tomato",
        "category":    "farm",
        "usable":      False,
    },
    54: {
        "id":          54,
        "name":        "Hạt Giống Dâu Tây",
        "icon":        "🍓",
        "price":       800,
        "description": "Thu hoạch sau 6 tiếng. Nguyên liệu Rượu Dâu cao cấp.",
        "db_key":      "seed_strawberry",
        "category":    "farm",
        "usable":      False,
    },
    55: {
        "id":          55,
        "name":        "Hạt Giống Bí Ngô",
        "icon":        "🎃",
        "price":       1200,
        "description": "Thu hoạch sau 8 tiếng. Nguyên liệu Mứt Bí Ngô thơm ngon.",
        "db_key":      "seed_pumpkin",
        "category":    "farm",
        "usable":      False,
    },
    56: {
        "id":          56,
        "name":        "Hạt Giống Hướng Dương",
        "icon":        "🌻",
        "price":       500,
        "description": "Lợi nhuận cao, thu hoạch sau 12 tiếng.",
        "db_key":      "seed_sunflower",
        "category":    "farm",
        "usable":      False,
    },
    57: {
        "id":          57,
        "name":        "Hạt Giống Ngôi Sao",
        "icon":        "⭐",
        "price":       2000,
        "description": "Cây hiếm với phần thưởng ngẫu nhiên, thu hoạch sau 24 tiếng.",
        "db_key":      "seed_star",
        "category":    "farm",
        "usable":      False,
    },
    61: {
        "id":          61,
        "name":        "Lootbox Common",
        "icon":        "<:lb_01_common:1535552629092913172>",
        "price":       500,
        "description": "Hộp may mắn phổ thông. Drop vật phẩm rank 0-1 từ fish/mine/chop.",
        "db_key":      "lb_61",
        "category":    "lootbox",
        "usable":      True,
    },
    62: {
        "id":          62,
        "name":        "Lootbox Uncommon",
        "icon":        "<:lb_02_uncommon:1535552631257174138>",
        "price":       1500,
        "description": "Hộp may mắn không phổ biến. Drop vật phẩm rank 0-2.",
        "db_key":      "lb_62",
        "category":    "lootbox",
        "usable":      True,
    },
    63: {
        "id":          63,
        "name":        "Lootbox Rare",
        "icon":        "<:lb_03_rare:1535552633660776509>",
        "price":       4000,
        "description": "Hộp may mắn hiếm. Drop vật phẩm rank 0-3, có thể ra Mực hoặc Quặng Vàng.",
        "db_key":      "lb_63",
        "category":    "lootbox",
        "usable":      True,
    },
    64: {
        "id":          64,
        "name":        "Lootbox Epic",
        "icon":        "<:lb_04_epic:1535552635778760774>",
        "price":       12000,
        "description": "Hộp may mắn sử thi. Drop vật phẩm rank 0-4, có thể ra Bạch Tuộc hay Kim Cương!",
        "db_key":      "lb_64",
        "category":    "lootbox",
        "usable":      True,
    },
    65: {
        "id":          65,
        "name":        "Lootbox Legendary",
        "icon":        "<:lb_05_legendary:1535552637850624011>",
        "price":       None,
        "description": "Hộp huyền thoại. Drop rank 0-5 với cơ hội ra Cá Huyền Thoại!",
        "db_key":      "lb_65",
        "category":    "lootbox",
        "usable":      True,
    },
    66: {
        "id":          66,
        "name":        "Lootbox Godly",
        "icon":        "<:lb_06_godly:1535552639834783764>",
        "price":       None,
        "description": "Hộp thần thánh siêu hiếm. Drop rank cao nhất + Bonus điểm/thẻ BM!",
        "db_key":      "lb_66",
        "category":    "lootbox",
        "usable":      True,
    },
    71: {
        "id":          71,
        "name":        "Salad Cà Chua",
        "icon":        "<:food_00_salad:1535658901222203512>",
        "price":       None,
        "description": "+ 30 Thể Lực ngay lập tức.",
        "db_key":      "food_70",
        "category":    "food",
        "usable":      True,
    },
    72: {
        "id":          72,
        "name":        "Súp Bí Ngô",
        "icon":        "<:food_01_pumpkin_soup:1535658903386202235>",
        "price":       None,
        "description": "+ 100% Tốc độ hồi thể lực trong 2h.",
        "db_key":      "food_71",
        "category":    "food",
        "usable":      True,
    },
    73: {
        "id":          73,
        "name":        "Cơm Cuộn Cá",
        "icon":        "<:food_02_fishrolls:1535658905433280614>",
        "price":       None,
        "description": "+ 20% Tỉ lệ rơi Lootbox trong 1h.",
        "db_key":      "food_72",
        "category":    "food",
        "usable":      True,
    },
    74: {
        "id":          74,
        "name":        "Sinh Tố Dâu",
        "icon":        "<:food_03_strawberry_smoothie:1535658907425316985>",
        "price":       None,
        "description": "+ 15% Tỉ lệ rơi Lootbox hiếm (Rare/Epic) trong 1h.",
        "db_key":      "food_73",
        "category":    "food",
        "usable":      True,
    },
    75: {
        "id":          75,
        "name":        "Khoai Tây Nghiền",
        "icon":        "<:food_04_mass_potato:1535658909543702668>",
        "price":       None,
        "description": "+ 1 Sản lượng thu hoạch nông trại trong 4h.",
        "db_key":      "food_74",
        "category":    "food",
        "usable":      True,
    },
    76: {
        "id":          76,
        "name":        "Cá Nướng Gỗ Thơm",
        "icon":        "<:food_05_cooked_carp:1535658912580116510>",
        "price":       None,
        "description": "+ 30% Tỉ lệ rơi Gỗ hiếm trong 1h.",
        "db_key":      "food_75",
        "category":    "food",
        "usable":      True,
    },
    77: {
        "id":          77,
        "name":        "Bánh Mì Thợ Mỏ",
        "icon":        "<:food_06_banh_mi:1535658914396377238>",
        "price":       None,
        "description": "+ 30% Tỷ lệ rơi Quặng hiếm trong 1h.",
        "db_key":      "food_76",
        "category":    "food",
        "usable":      True,
    },
    78: {
        "id":          78,
        "name":        "Bánh Bí Ngô Hấp",
        "icon":        "<:food_07_pumpkin_pie:1535658916434681986>",
        "price":       None,
        "description": "+ 15% Tỉ lệ rơi Cá hiếm trong 1h.",
        "db_key":      "food_77",
        "category":    "food",
        "usable":      True,
    },
    79: {
        "id":          79,
        "name":        "Trà Hướng Dương",
        "icon":        "<:food_08_sun_tea:1535658918603395092>",
        "price":       None,
        "description": "- 1 Thể lực tiêu hao cho MỌI hành động trong 1h.",
        "db_key":      "food_78",
        "category":    "food",
        "usable":      True,
    },
    80: {
        "id":          80,
        "name":        "Lẩu Thập Cẩm",
        "icon":        "<:food_09_trout_soup:1535658920591368232>",
        "price":       None,
        "description": "+ 35% Tỉ lệ rơi Đồ hiếm (Tất cả hoạt động) trong 2h.",
        "db_key":      "food_79",
        "category":    "food",
        "usable":      True,
    },
}

def get_item_by_id(item_id: int):
    return ITEM_REGISTRY.get(item_id)

def get_item_by_db_key(db_key: str):
    for item in ITEM_REGISTRY.values():
        if item["db_key"] == db_key:
            return item
    return None

def get_items_by_category(category: str):
    return sorted([item for item in ITEM_REGISTRY.values() if item['category'] == category], key=lambda x: x['id'])

def get_buyable_items(category: str):
    return [item for item in get_items_by_category(category) if item['price'] is not None]

